#!/bin/sh
# Aghpbu
#find ~ Anime-Girls-Holding-Programming-Books -type d -maxdepth 2
cd ~
ErrorMsgBase="Error: "

#Install
Install(){
        echo "Installing Anime-Girls-Holding-Programming-Books..."
        cd ~/Pictures

        Dir=Anime-Girls-Holding-Programming-Books
        if [ -d $Dir ]; then
                echo  $ErrorMsgBase"The file already exist" | sed $'s/Error: /\033[0;31m&\e[0m/'
               # echo 'Hello World!' | sed $'s/World/\e[1m&\e[0m/'
        else
                git clone https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books.git
                echo "Installation complete the diretory is install in ~/Pictures"
        fi
}

#Update
update(){
echo -e "Analyzing Home folder for Anime-Girls-Holding-Programming-Books..."
FILES=`find $(pwd) -maxdepth 1 -type d -not -path '*/\.*' | sort `>& /dev/null
for f in $FILES
do
    echo -e "Analyzing $f...">& /dev/null

    
    #find Anime-Girls-Holding-Programming-Books -maxdepth 0 
    DIRECTORY=$f/Anime-Girls-Holding-Programming-Books
         if [ -d "$DIRECTORY" ]; then
			 

# See if there are any incoming changes
    cd Pictures/Anime-Girls-Holding-Programming-Books
    currentVer= git rev-parse --short HEAD &> /dev/null
    updatesVer= git rev-parse --short origin/master &> /dev/null
	if [ $currentVer -ne $updatesVer ]; then

        echo -e "\033[00;36mThose files will be added: \e[0m"
       git diff  --diff-filter=A --name-only  -a  master..origin/HEAD >updates.txt
       input="updates.txt"
        echo -e
        while IFS= read -r line
        do
                echo -e "\033[00;35m* $line\e[0m"
        done < "$input"
        echo -e
        rm $input
        fi
        else
            echo -e "\033[00;32mYou are up to date.\e[0m"
            break
            fi
         echo "Anime-Girls-Holding-Programming-Books is present. Do you want to update it ? (y/n):  "
        read
         if [[ $REPLY == "y" || $REPLY ==  "Y" ]]; then
                 cd $DIRECTORY
                 #pwd 
                 echo "Updating the waifus..."| sed $'s/Updating the waifus... /\033[0;34m&\e[0m/ '  
                  git pull  https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books.git
                 echo "Update complete"  
                 break
         fi
         if [[  $REPLY == "n" || $REPLY == "N" ]];then
                exit
         fi
        if [[ $REPLY != "y" || $REPLY != "Y" || $REPLY != "n" || $REPLY != "N" ]];then
                echo "Invalid input. Please enter y or n"
                read
                if [[ $REPLY == "y" || $REPLY ==  "Y" ]]; then
                 cd $DIRECTORY
                 pwd 
                 echo "Updating the waifus..." 
                 git pull  https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books.git
                 echo "Update complete"  
                 break
                fi
                   if [[  $REPLY == "n" || $REPLY == "N" ]];then
                exit
         fi

         fi 

done
}
Help(){
        while IFS= read -r line; do
	    printf "%s\n" "$line"
	done <<-EOF
	Usage:
	    ${0##*/} -i
	    ${0##*/} -u
	    ${0##*/} -h
	
	Options:
	    -h show help
	    -U Update
	    -I Install
	EOF

}
while getopts 'vq:iuhVa:' OPT; do
        case $OPT in
                u)
                        update
                        exit 0   
                         ;;
                i)
                        Install
                        exit 0
                         ;;
                 *)
                        Help
                        exit 1
                        ;;
	esac
done
shift $((OPTIND - 1))
